server:
  port: 9001

spring:
  application:
    name: soboriane
    version: 0.0.1
  mvc:
    view:
      prefix:
      suffix: .html
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: soboriane
  liquibase:
    enabled: ${LIQUIBASE:true}
    default-schema: soboriane
    liquibase-schema: liquibase
    change-log: db/changelog/db.changelog-master.xml

app:
  client-configuration:
    endpoint: "/ws-work"
    brokerPrefix:
      "/topic"
    applicationPrefix: "/app"
    userPrefix: "/user"
    topic: "/topic/message"
    max-retry-connect: 5
    time-out-value: 5000

logging:
  level:
    root: info
    web: trace
    com.mikesoft.soboriane: trace


