server:
  port: 9001

spring:
  application:
    name: soboriane
    version: 0.0.1
  mvc:
    view:
      prefix:
      suffix: .html
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: soboriane
  liquibase:
    enabled: ${LIQUIBASE:true}
    default-schema: soboriane
    liquibase-schema: liquibase
    change-log: db/changelog/db.changelog-master.xml

app:
  web-socket-configuration:
    enable-simple-broker: "/topic"
    application-destination-prefixes: "/app"
    updates: "/topic/message"
    endpoint: "/ws-work"
  client:
    socket-name: "${app.web-socket-configuration.endpoint}"
    topic: "${app.web-socket-configuration.updates}"
    max-retry-connect: 5
    time-out-value: 5000

logging:
  level:
    root: info
    web: trace
    com.mikesoft.soboriane: trace


